In [4]:
import pandas as pd

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
data = pd.read_csv('/home/kiran/Downloads/cleaned-data/LARPDatabase_2015.csv')

In [9]:
data

,Unnamed: 0,MANAGEMENT,VESSEL,REF NO,OCCURRENCE DATE,STATUS,AREA OF CONCERN,DESCRIPTION,IMMEDIATE ACTION TAKEN,CATEGORY,...,LARP SAFETY DEVICE,WORK ENVIRONMENT,HOUSE KEEPING,PERMIT TO WORK,LARP PPE,WORK POSITION,REPORTED BY,CLOSURE REMARK,CLOSURE DATE,CLOSED BY
0,0,SMPL - Chennai,NANYANG STAR,LR/NAST/2018/98,2018-04-22 03:05:14.000,Accepted,Safety Management (LSA & FFA) and security - C...,Personnel Entering Battery room without infor...,Dangers of working alone without informing OOW...,Unsafe act,...,NaN,NaN,NaN,NaN,NaN,NaN,Arun Kumar Moorthy,NaN,NaN,NaN
1,1,SMPL - Chennai,DEE4 BIRCH,LR/FRHA/2018/152,2018-08-18 09:21:47.000,Accepted,Safety Management (LSA & FFA) and security - C...,EXPIRED FOOD IN ECR WAS FOUND BEING USED. IMME...,NaN,Safe act,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,SMPL - Chennai,NANYANG STAR,LR/NAST/2018/153,2018-05-20 08:35:46.000,Accepted,General Appearance and condition - Ch 12,during drill found SCBA bottles pressure less ...,informed the person incharge and immediately h...,Unsafe act,...,NaN,NaN,NaN,NaN,NaN,NaN,Suresh Velayutham,NaN,NaN,NaN
3,3,SMPL - Chennai,VELOS SAPPHIRE,LR/GRVIC/2015/106,2015-12-07 09:54:27.000,Accepted,Safety Management (LSA & FFA) and security - C...,50 ltrs gear oil in half cut drum left open on...,Shifted properly,Unsafe act,...,NaN,NaN,Not secured,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,SMSL - Singapore,BENFICA,LR/BNFC/2018/3,2018-01-16 10:45:21.000,Accepted,Safety Management (LSA & FFA) and security - C...,Deck crew properly secured the hydroblast mach...,NaN,Safe act,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61045,61068,SMSL - Singapore,BULK HOLLAND,LR/BUHD/2018/126,2018-12-28 13:50:04.000,Accepted,Ch V/Safety Management- (Enclosed space entry ...,one crew open the paint store room to get some...,one crew stop him and advice to ventilate it f...,Unsafe act,...,NaN,Lack of ventilation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61046,61069,SMPL - Chennai,GAS STELLA,LR/STGS/2018/81,2018-09-11 21:35:08.000,Accepted,Mooring - Ch 9 b. Mooring practices,While mooring operation at Inchon winch gear s...,Immediately mooring winch was stopped and safe...,Unsafe act,...,NaN,NaN,NaN,NaN,NaN,NaN,Shashi Kant Singh,NaN,NaN,NaN
61047,61070,SMPL - Chennai,APL FLORIDA,LR/AFLO/2019/85,2019-08-13 04:03:58.000,Accepted,Ch X/ Engine & Steering Compartment- (Safety M...,it was observed that while opening Main engine...,"stopped the person immediately, released the p...",Unsafe act,...,NaN,NaN,NaN,NaN,NaN,NaN,Rajesh Sugumar,NaN,NaN,NaN
61048,61071,SMPL - Chennai,DEE4 CEDAR,LR/ORST/2018/283,2018-10-14 06:57:36.000,Accepted,Safety Management (LSA & FFA) and security - C...,when carrying out hydroblasting on main deck i...,Immediately informed hod and and explained the...,Unsafe act,...,NaN,NaN,NaN,NaN,NaN,NaN,Aditya Kotwal,NaN,NaN,NaN
61049,61072,SMPL - Chennai,CASTARA,LR/CAST/2019/47,2019-04-20 15:06:19.000,Accepted,"Ch V/Safety Management- (Drills, Training and ...",A crew member was found closing a steam trace ...,He was asked to stop and use leather gloves.,Unsafe act,...,NaN,NaN,NaN,NaN,Arms/Hands,NaN,Raghavendra Ramadas,NaN,NaN,NaN

In [10]:
data.columns

Index(['Unnamed: 0', 'MANAGEMENT', 'VESSEL', 'REF NO', 'OCCURRENCE DATE',
       'STATUS', 'AREA OF CONCERN', 'DESCRIPTION', 'IMMEDIATE ACTION TAKEN',
       'CATEGORY', 'WORK EQUIPMENT', 'LARP PROCEDURE', 'LARP SAFETY DEVICE',
       'WORK ENVIRONMENT', 'HOUSE KEEPING', 'PERMIT TO WORK', 'LARP PPE',
       'WORK POSITION', 'REPORTED BY', 'CLOSURE REMARK', 'CLOSURE DATE',
       'CLOSED BY'],
      dtype='str')

In [11]:
data.describe()

         Unnamed: 0
count  61050.000000
mean   30533.025880
std    17630.477551
min        0.000000
25%    15265.250000
50%    30530.500000
75%    45798.750000
max    61072.000000

In [12]:
data.columns

Index(['Unnamed: 0', 'MANAGEMENT', 'VESSEL', 'REF NO', 'OCCURRENCE DATE',
       'STATUS', 'AREA OF CONCERN', 'DESCRIPTION', 'IMMEDIATE ACTION TAKEN',
       'CATEGORY', 'WORK EQUIPMENT', 'LARP PROCEDURE', 'LARP SAFETY DEVICE',
       'WORK ENVIRONMENT', 'HOUSE KEEPING', 'PERMIT TO WORK', 'LARP PPE',
       'WORK POSITION', 'REPORTED BY', 'CLOSURE REMARK', 'CLOSURE DATE',
       'CLOSED BY'],
      dtype='str')

In [14]:
data['Unnamed: 0'].isna().sum()

np.int64(0)

In [15]:
data = data.drop(columns=['Unnamed: 0'])

In [16]:
data.columns

Index(['MANAGEMENT', 'VESSEL', 'REF NO', 'OCCURRENCE DATE', 'STATUS',
       'AREA OF CONCERN', 'DESCRIPTION', 'IMMEDIATE ACTION TAKEN', 'CATEGORY',
       'WORK EQUIPMENT', 'LARP PROCEDURE', 'LARP SAFETY DEVICE',
       'WORK ENVIRONMENT', 'HOUSE KEEPING', 'PERMIT TO WORK', 'LARP PPE',
       'WORK POSITION', 'REPORTED BY', 'CLOSURE REMARK', 'CLOSURE DATE',
       'CLOSED BY'],
      dtype='str')

In [18]:
data['MANAGEMENT'].value_counts()

MANAGEMENT
SMPL - Chennai      42367
SMSL - Singapore     9069
SNSPL - Pune         5029
SOS - Kochi          3619
Name: count, dtype: int64

In [24]:
data['VESSEL']

0          NANYANG STAR
1            DEE4 BIRCH
2          NANYANG STAR
3        VELOS SAPPHIRE
4               BENFICA
              ...
61045      BULK HOLLAND
61046        GAS STELLA
61047       APL FLORIDA
61048        DEE4 CEDAR
61049           CASTARA
Name: VESSEL, Length: 61050, dtype: str

In [26]:
data['REF NO'].value_counts()

REF NO
LR/NAST/2018/98      1
LR/FRHA/2018/152     1
LR/NAST/2018/153     1
LR/GRVIC/2015/106    1
LR/BNFC/2018/3       1
                    ..
LR/BUHD/2018/126     1
LR/STGS/2018/81      1
LR/AFLO/2019/85      1
LR/ORST/2018/283     1
LR/CAST/2019/47      1
Name: count, Length: 61050, dtype: int64

In [27]:
data.columns

Index(['MANAGEMENT', 'VESSEL', 'REF NO', 'OCCURRENCE DATE', 'STATUS',
       'AREA OF CONCERN', 'DESCRIPTION', 'IMMEDIATE ACTION TAKEN', 'CATEGORY',
       'WORK EQUIPMENT', 'LARP PROCEDURE', 'LARP SAFETY DEVICE',
       'WORK ENVIRONMENT', 'HOUSE KEEPING', 'PERMIT TO WORK', 'LARP PPE',
       'WORK POSITION', 'REPORTED BY', 'CLOSURE REMARK', 'CLOSURE DATE',
       'CLOSED BY'],
      dtype='str')

In [28]:
data['OCCURRENCE DATE']

0        2018-04-22 03:05:14.000
1        2018-08-18 09:21:47.000
2        2018-05-20 08:35:46.000
3        2015-12-07 09:54:27.000
4        2018-01-16 10:45:21.000
                  ...
61045    2018-12-28 13:50:04.000
61046    2018-09-11 21:35:08.000
61047    2019-08-13 04:03:58.000
61048    2018-10-14 06:57:36.000
61049    2019-04-20 15:06:19.000
Name: OCCURRENCE DATE, Length: 61050, dtype: str

In [29]:
data['OCCURRENCE DATE'] = pd.to_datetime(data['OCCURRENCE DATE'])
data['OCCURRENCE DATE'] = data['OCCURRENCE DATE'].dt.strftime('%Y-%m-%d %H:%M:%S')

In [30]:
data['OCCURRENCE DATE']

0        2018-04-22 03:05:14
1        2018-08-18 09:21:47
2        2018-05-20 08:35:46
3        2015-12-07 09:54:27
4        2018-01-16 10:45:21
                ...
61045    2018-12-28 13:50:04
61046    2018-09-11 21:35:08
61047    2019-08-13 04:03:58
61048    2018-10-14 06:57:36
61049    2019-04-20 15:06:19
Name: OCCURRENCE DATE, Length: 61050, dtype: str

In [31]:
data.columns

Index(['MANAGEMENT', 'VESSEL', 'REF NO', 'OCCURRENCE DATE', 'STATUS',
       'AREA OF CONCERN', 'DESCRIPTION', 'IMMEDIATE ACTION TAKEN', 'CATEGORY',
       'WORK EQUIPMENT', 'LARP PROCEDURE', 'LARP SAFETY DEVICE',
       'WORK ENVIRONMENT', 'HOUSE KEEPING', 'PERMIT TO WORK', 'LARP PPE',
       'WORK POSITION', 'REPORTED BY', 'CLOSURE REMARK', 'CLOSURE DATE',
       'CLOSED BY'],
      dtype='str')

In [33]:
data['STATUS'].value_counts()

STATUS
Accepted    57159
Open         3521
Rejected      370
Name: count, dtype: int64

In [34]:
data['AREA OF CONCERN'].value_counts()

AREA OF CONCERN
Safety Management (LSA & FFA) and security - Ch 5 d. COWSP                                      9587
Ch V/Safety Management- (Reporting- LARP, Near Misses, Incident Investigations and PSC etc.)    3210
Ch I GENERAL INFORMATION                                                                        2186
General Appearance and condition - Ch 12                                                        2074
Ch V/Safety Management- (Safe Access)                                                           1546
                                                                                                ...
Ch VIII/ Cargo & Ballast System- (Cargo compressor and Motor Room)-LPG                             3
Ch VIII/ Cargo & Ballast System- (Crude oil washing)                                               3
Ch VIII/ Cargo & Ballast System- (Pressure relief and venting system)-LPG                          2
Ch VIII/ Cargo & Ballast System- (Void space and seal Type C cargo tanks)-LPG                      1
Ch IX/ Mooring- (Emergency towing arrangement)                                                     1
Name: count, Length: 117, dtype: int64

In [35]:
data.columns

Index(['MANAGEMENT', 'VESSEL', 'REF NO', 'OCCURRENCE DATE', 'STATUS',
       'AREA OF CONCERN', 'DESCRIPTION', 'IMMEDIATE ACTION TAKEN', 'CATEGORY',
       'WORK EQUIPMENT', 'LARP PROCEDURE', 'LARP SAFETY DEVICE',
       'WORK ENVIRONMENT', 'HOUSE KEEPING', 'PERMIT TO WORK', 'LARP PPE',
       'WORK POSITION', 'REPORTED BY', 'CLOSURE REMARK', 'CLOSURE DATE',
       'CLOSED BY'],
      dtype='str')

In [37]:
data['DESCRIPTION'].isna().sum()

np.int64(17)

In [38]:
data.columns

Index(['MANAGEMENT', 'VESSEL', 'REF NO', 'OCCURRENCE DATE', 'STATUS',
       'AREA OF CONCERN', 'DESCRIPTION', 'IMMEDIATE ACTION TAKEN', 'CATEGORY',
       'WORK EQUIPMENT', 'LARP PROCEDURE', 'LARP SAFETY DEVICE',
       'WORK ENVIRONMENT', 'HOUSE KEEPING', 'PERMIT TO WORK', 'LARP PPE',
       'WORK POSITION', 'REPORTED BY', 'CLOSURE REMARK', 'CLOSURE DATE',
       'CLOSED BY'],
      dtype='str')

In [41]:
data['IMMEDIATE ACTION TAKEN'].value_counts()

IMMEDIATE ACTION TAKEN
1                                                                                                                                                                 960
Stopped and consequences discussed.                                                                                                                                48
stopped and consequences discussed.                                                                                                                                46
appreciated                                                                                                                                                        15
STOPPED AND CONSEQUENCES DISCUSSED.                                                                                                                                14
                                                                                                                                                                 ...
one crew stop him and advice to ventilate it first before entering, fumes and hazardous substances may present at the air inside, lack of oxygen may possible.      1
Immediately mooring winch was stopped and safety pin was put in place.                                                                                              1
stopped the person immediately, released the pressure and resumed the work again.                                                                                   1
Immediately informed hod and and explained the consequence of this action will lead to serious injury resulting in a major accident.                                1
He was asked to stop and use leather gloves.                                                                                                                        1
Name: count, Length: 51118, dtype: int64

In [42]:
data.columns

Index(['MANAGEMENT', 'VESSEL', 'REF NO', 'OCCURRENCE DATE', 'STATUS',
       'AREA OF CONCERN', 'DESCRIPTION', 'IMMEDIATE ACTION TAKEN', 'CATEGORY',
       'WORK EQUIPMENT', 'LARP PROCEDURE', 'LARP SAFETY DEVICE',
       'WORK ENVIRONMENT', 'HOUSE KEEPING', 'PERMIT TO WORK', 'LARP PPE',
       'WORK POSITION', 'REPORTED BY', 'CLOSURE REMARK', 'CLOSURE DATE',
       'CLOSED BY'],
      dtype='str')

In [45]:
data['CATEGORY'].value_counts()

CATEGORY
Unsafe act    48465
Safe act      12585
Name: count, dtype: int64

In [46]:
data.columns

Index(['MANAGEMENT', 'VESSEL', 'REF NO', 'OCCURRENCE DATE', 'STATUS',
       'AREA OF CONCERN', 'DESCRIPTION', 'IMMEDIATE ACTION TAKEN', 'CATEGORY',
       'WORK EQUIPMENT', 'LARP PROCEDURE', 'LARP SAFETY DEVICE',
       'WORK ENVIRONMENT', 'HOUSE KEEPING', 'PERMIT TO WORK', 'LARP PPE',
       'WORK POSITION', 'REPORTED BY', 'CLOSURE REMARK', 'CLOSURE DATE',
       'CLOSED BY'],
      dtype='str')

In [48]:
data['WORK EQUIPMENT'].isna().sum()

np.int64(54445)

In [50]:
data.drop(columns=['WORK EQUIPMENT'], inplace=True)

In [51]:
data.columns

Index(['MANAGEMENT', 'VESSEL', 'REF NO', 'OCCURRENCE DATE', 'STATUS',
       'AREA OF CONCERN', 'DESCRIPTION', 'IMMEDIATE ACTION TAKEN', 'CATEGORY',
       'LARP PROCEDURE', 'LARP SAFETY DEVICE', 'WORK ENVIRONMENT',
       'HOUSE KEEPING', 'PERMIT TO WORK', 'LARP PPE', 'WORK POSITION',
       'REPORTED BY', 'CLOSURE REMARK', 'CLOSURE DATE', 'CLOSED BY'],
      dtype='str')

In [54]:
data['LARP PROCEDURE']

0                 NaN
1                 NaN
2                 NaN
3        Not followed
4                 NaN
             ...
61045       Not aware
61046    Not followed
61047    Not followed
61048    Not followed
61049    Not followed
Name: LARP PROCEDURE, Length: 61050, dtype: str

In [56]:
data['LARP SAFETY DEVICE'].isna().sum()

np.int64(54339)

In [57]:
data.drop(columns = ['LARP SAFETY DEVICE'], inplace=True)

In [58]:
data.columns

Index(['MANAGEMENT', 'VESSEL', 'REF NO', 'OCCURRENCE DATE', 'STATUS',
       'AREA OF CONCERN', 'DESCRIPTION', 'IMMEDIATE ACTION TAKEN', 'CATEGORY',
       'LARP PROCEDURE', 'WORK ENVIRONMENT', 'HOUSE KEEPING', 'PERMIT TO WORK',
       'LARP PPE', 'WORK POSITION', 'REPORTED BY', 'CLOSURE REMARK',
       'CLOSURE DATE', 'CLOSED BY'],
      dtype='str')

In [ ]:
data