In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
data = pd.read_csv('/home/kiran/Downloads/cleaned-data/Raw-Data/NewMergedNearMiss_3.1.csv')

In [4]:
data

,NME ID,Ref.No.,Name of Ship,Type of Ship,Date of Report,Delay (in days),Description of the incident and cause analysis,Location,Probability of Reoccurence,Cause Analysis,...,IndirectCause,RootCause,RevisedIncidentCategory,LessionLearnt,ReviewComments,ClosingNote,ClosingDate,Incident_Category_Potential,Probability_of_Reoccurence,Port Country Name
0,NME100000,CAL-01/2012,APL CALIFORNIA,CONTAINER,2012-01-03,0.0,On 03 Jan 2012 @ 0254 hrs vessel berthed at qi...,Galley,Likely,Suspect undeclared machinery stowed inside a c...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marginal-Moderate-Medium,Likely-High-Medium-Moderate,NaN
1,NME100001,CHI-01/2012,TS CHINA,CONTAINER,2012-01-05,0.0,"The ship departed port of osaka ,and main engi...",Machinery Room,Very Low,Failure to follow repair / maintenance instruc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Critical-Severe,Very Unlikely-Very Low,NaN
2,NME100002,CHI-02/2012,TS CHINA,CONTAINER,2012-01-06,0.0,While the Ship was in Port ( NAGOYA - JAPAN ) ...,Machinery Room,Very Low,Failure to follow repair/maintenance instructi...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marginal-Moderate-Medium,Very Unlikely-Very Low,NaN
3,NME100003,FLD-01-2012,APL FLORIDA,CONTAINER,2012-01-09,2.0,"Vessel approaching berth at Yokohama,Japan wit...",Bridge,Very Low,"Prior arrival to Yokohama, vessel had very bad...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor-Low-Slight,Very Unlikely-Very Low,NaN
4,NME100004,CAP-001/12,CALA PINGUINO,CONTAINER,2012-01-23,16.0,AFT TUG LINE PARTED WHILE DEPARTING PUERTO CAB...,Mooring Area,Very Likely,Duty Officer should always check the quality o...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor-Low-Slight,Very Likely-Very High,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12441,NME112441,NM/NBAL/2020/Apr/4,NORD BALTIC,NAN,2020-04-12 17:43:37.050,NaN,Stevedores about to transfer shore escavator u...,Sea,Likely,NaN,...,NaN,NaN,NaN,NaN,NaN,Thank you for being vigilant and devoting time...,2020-04-29 00:00:00,Marginal-Moderate-Medium,Likely-High-Medium-Moderate,NaN
12442,NME112442,NM/NSFX/2020/Apr/6,NAVIOS FELIX,NAN,2020-04-21 06:22:51.907,NaN,"During Safety around checked, 4/E was focussin...",Sea,Unlikely,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Catastrophic-Major-Extreme,Unlikely-Low-Marginal,NaN
12443,NME112443,NM/VOLN/2020/Apr/7,VOLANTE,NAN,2020-04-30 12:20:24.683,NaN,During routine round of the engine room it was...,Sea,Likely,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor-Low-Slight,Likely-High-Medium-Moderate,NaN
12444,NME112444,NM/HOUM/2020/Apr/8,HOURAI MARU,NAN,2020-04-24 13:43:40.970,NaN,While casting off the tug at aft station the t...,Port,Unlikely,NaN,...,NaN,NaN,NaN,NaN,NaN,UNSAFE CONDITION.NM Closed,2020-05-11 00:00:00,Minor-Low-Slight,Unlikely-Low-Marginal,NaN
12445,NME112445,NM/LORD/2020/May/3,BW LORD,NAN,2020-05-02 17:40:18.397,NaN,High pressure hydroblasting hose ruptured and ...,Sea,Very Likely,NaN,...,NaN,NaN,NaN,NaN,NaN,High pressure hoses shall be checked thoroughl...,2020-06-01 00:00:00,Marginal-Moderate-Medium,Very Likely-Very High,NaN

In [5]:
data.columns

Index(['NME ID', 'Ref.No.', 'Name of Ship', 'Type of Ship', 'Date of Report',
       'Delay (in days)', 'Description of the incident and cause analysis',
       'Location', 'Probability of Reoccurence', 'Cause Analysis',
       'Counter measure to prevent recurrence',
       'Suggested Corrective Action (Office Use)',
       'Date Corrective action completed', 'Area of Concern',
       'Date Investigation Commenced', 'Target Date',
       'Date of Investigation Completion', 'Extension (if any) with remarks',
       'Time Period (in days)', 'Status', 'Master', 'Chief Engineer',
       'Superintendent', 'Details of potential loss Category',
       'Date of Near Miss', 'year', 'PIC', 'Port Name', 'Related Department',
       'Description of event leading to the incident',
       'Immediate action taken', 'Potential extent of damage/injury',
       'Potential Damage category', 'Potential Damage subcategory',
       'Immediate action initiated', 'Learning Potential',
       'Severity of incident', 'External authority reporting required',
       'Further Investigation Required', 'Corrective Action',
       'Incident communicated to oil majors',
       'Potential incident to be shared with industry', 'Due Date',
       'Status of CA', 'Closure Date - CA', 'Remarks - CA', 'Report Type',
       'DirectCause', 'IndirectCause', 'RootCause', 'RevisedIncidentCategory',
       'LessionLearnt', 'ReviewComments', 'ClosingNote', 'ClosingDate',
       'Incident_Category_Potential', 'Probability_of_Reoccurence',
       'Port Country Name'],
      dtype='str')

In [3]:
data

,NME ID,Ref.No.,Name of Ship,Type of Ship,Date of Report,Delay (in days),Description of the incident and cause analysis,Location,Probability of Reoccurence,Cause Analysis,...,IndirectCause,RootCause,RevisedIncidentCategory,LessionLearnt,ReviewComments,ClosingNote,ClosingDate,Incident_Category_Potential,Probability_of_Reoccurence,Port Country Name
0,NME100000,CAL-01/2012,APL CALIFORNIA,CONTAINER,2012-01-03,0.0,On 03 Jan 2012 @ 0254 hrs vessel berthed at qi...,Galley,Likely,Suspect undeclared machinery stowed inside a c...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marginal-Moderate-Medium,Likely-High-Medium-Moderate,NaN
1,NME100001,CHI-01/2012,TS CHINA,CONTAINER,2012-01-05,0.0,"The ship departed port of osaka ,and main engi...",Machinery Room,Very Low,Failure to follow repair / maintenance instruc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Critical-Severe,Very Unlikely-Very Low,NaN
2,NME100002,CHI-02/2012,TS CHINA,CONTAINER,2012-01-06,0.0,While the Ship was in Port ( NAGOYA - JAPAN ) ...,Machinery Room,Very Low,Failure to follow repair/maintenance instructi...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marginal-Moderate-Medium,Very Unlikely-Very Low,NaN
3,NME100003,FLD-01-2012,APL FLORIDA,CONTAINER,2012-01-09,2.0,"Vessel approaching berth at Yokohama,Japan wit...",Bridge,Very Low,"Prior arrival to Yokohama, vessel had very bad...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor-Low-Slight,Very Unlikely-Very Low,NaN
4,NME100004,CAP-001/12,CALA PINGUINO,CONTAINER,2012-01-23,16.0,AFT TUG LINE PARTED WHILE DEPARTING PUERTO CAB...,Mooring Area,Very Likely,Duty Officer should always check the quality o...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor-Low-Slight,Very Likely-Very High,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12441,NME112441,NM/NBAL/2020/Apr/4,NORD BALTIC,NAN,2020-04-12 17:43:37.050,NaN,Stevedores about to transfer shore escavator u...,Sea,Likely,NaN,...,NaN,NaN,NaN,NaN,NaN,Thank you for being vigilant and devoting time...,2020-04-29 00:00:00,Marginal-Moderate-Medium,Likely-High-Medium-Moderate,NaN
12442,NME112442,NM/NSFX/2020/Apr/6,NAVIOS FELIX,NAN,2020-04-21 06:22:51.907,NaN,"During Safety around checked, 4/E was focussin...",Sea,Unlikely,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Catastrophic-Major-Extreme,Unlikely-Low-Marginal,NaN
12443,NME112443,NM/VOLN/2020/Apr/7,VOLANTE,NAN,2020-04-30 12:20:24.683,NaN,During routine round of the engine room it was...,Sea,Likely,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor-Low-Slight,Likely-High-Medium-Moderate,NaN
12444,NME112444,NM/HOUM/2020/Apr/8,HOURAI MARU,NAN,2020-04-24 13:43:40.970,NaN,While casting off the tug at aft station the t...,Port,Unlikely,NaN,...,NaN,NaN,NaN,NaN,NaN,UNSAFE CONDITION.NM Closed,2020-05-11 00:00:00,Minor-Low-Slight,Unlikely-Low-Marginal,NaN
12445,NME112445,NM/LORD/2020/May/3,BW LORD,NAN,2020-05-02 17:40:18.397,NaN,High pressure hydroblasting hose ruptured and ...,Sea,Very Likely,NaN,...,NaN,NaN,NaN,NaN,NaN,High pressure hoses shall be checked thoroughl...,2020-06-01 00:00:00,Marginal-Moderate-Medium,Very Likely-Very High,NaN

In [4]:
data['Area of Concern']

0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                         Mooring
                   ...
12441    Cargo And Ballast System
12442                         NaN
12443                         NaN
12444                     Mooring
12445           Safety Management
Name: Area of Concern, Length: 12446, dtype: str

In [5]:
data['Area of Concern'].value_counts()

Area of Concern
Safety Management                4112
Engine & Steering Compartment    1216
Mooring                          1052
Cargo And Ballast System          802
Navigation                        523
General App & Condition           484
Others                            453
Cowsp                             212
Crew Management                   172
Environment                       129
Company Documents                  87
Communication                      75
Planned Maintenance                25
Monitoring                         23
Execution & Monitoring             13
Lack Of Procedure                   6
Annexure 1 To Annexure 6            4
Name: count, dtype: int64

In [6]:
data['Area of Concern'].isnull().sum()

np.int64(3058)

In [7]:
data['Cause Analysis']

0        Suspect undeclared machinery stowed inside a c...
1        Failure to follow repair / maintenance instruc...
2        Failure to follow repair/maintenance instructi...
3        Prior arrival to Yokohama, vessel had very bad...
4        Duty Officer should always check the quality o...
                               ...
12441                                                  NaN
12442                                                  NaN
12443                                                  NaN
12444                                                  NaN
12445                                                  NaN
Name: Cause Analysis, Length: 12446, dtype: str

In [8]:
data['Cause Analysis'].isnull().sum()

np.int64(7510)

In [10]:
data['Chief Engineer'].value_counts()

Chief Engineer
C/E.SelvaKumar                 46
PRS Nair                       31
Molano Alan                    26
Jiby Joseph                    24
Thirunavkkarasu chezhain       24
                               ..
Ruhul rai                       1
Rahul                           1
Mr James Martin                 1
Gulshan Singh Ramkala Singh     1
Felix B. Climaco                1
Name: count, Length: 300, dtype: int64

In [11]:
data['Chief Engineer'].isna().sum()

np.int64(11406)

In [13]:
data['ClosingDate'].value_counts()

ClosingDate
2017-05-15 00:00:00    41
2019-08-13 00:00:00    40
2016-09-15 00:00:00    32
2019-05-20 00:00:00    31
2014-11-25 00:00:00    29
                       ..
2020-05-21 00:00:00     1
2020-04-19 00:00:00     1
2020-03-11 00:00:00     1
2020-04-09 00:00:00     1
2020-05-27 00:00:00     1
Name: count, Length: 1153, dtype: int64

In [14]:
data['ClosingDate'] = pd.to_datetime(data['ClosingDate']).dt.date

In [16]:
data['ClosingDate'].isna().sum()

np.int64(7084)

In [17]:
data['ClosingNote'].head()

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: ClosingNote, dtype: str

In [19]:
data['Closure Date - CA']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
12441    NaN
12442    NaN
12443    NaN
12444    NaN
12445    NaN
Name: Closure Date - CA, Length: 12446, dtype: str

In [20]:
data['Closure Date - CA'].isna().sum()

np.int64(12191)

In [21]:
data['Corrective Action'].head()

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: Corrective Action, dtype: str

In [22]:
data['Corrective Action'].isna().sum()

np.int64(9634)

In [24]:
data['Counter measure to prevent recurrence'].head()

0    1. All cargo holds to be inspected throughly o...
1    All duty engineers and duty oilers instruct to...
2    Notice Being Posted near all A/E's that " Star...
3    After heavy weather all LSA-FFA fittings to be...
4    All crew atfwd&aft station to be positioned we...
Name: Counter measure to prevent recurrence, dtype: str

In [26]:
data['Date Corrective action completed'].head()

0                28/5/12
1                    NaN
2                    NaN
3                    NaN
4    2012-05-21 00:00:00
Name: Date Corrective action completed, dtype: str

In [27]:
data['Date Corrective action completed'].value_counts()

Date Corrective action completed
2013-08-13 00:00:00    26
2013-08-14 00:00:00    20
2013-09-18 00:00:00    19
2012-05-25 00:00:00    18
2013-10-14 00:00:00    18
                       ..
10-01-2015              1
21-11-2014              1
04-08-2014              1
23-07-2014              1
18-08-2014              1
Name: count, Length: 305, dtype: int64

In [28]:
data['Date Corrective action completed'] = pd.to_datetime(
    data['Date Corrective action completed'],
    errors='coerce',
    dayfirst=True
)

/tmp/ipykernel_4517/4054992174.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Date Corrective action completed'] = pd.to_datetime(

In [30]:
data['Date Corrective action completed'] = data['Date Corrective action completed'].dt.date

In [31]:
data['Date Corrective action completed'].value_counts()

Date Corrective action completed
2013-08-13    26
2013-08-14    20
2013-09-18    19
2012-05-25    18
2013-10-14    18
              ..
2015-01-10     1
2014-11-21     1
2014-08-04     1
2014-07-23     1
2014-08-18     1
Name: count, Length: 287, dtype: int64

In [32]:
data['year'] = pd.to_datetime(data['Date Corrective action completed']).dt.year
data['month'] = pd.to_datetime(data['Date Corrective action completed']).dt.month

In [33]:
data['Date Investigation Commenced']

0        2012-01-03
1        2012-01-05
2        2012-01-05
3        2012-01-10
4               NaN
            ...
12441           NaN
12442           NaN
12443           NaN
12444           NaN
12445           NaN
Name: Date Investigation Commenced, Length: 12446, dtype: str

In [34]:
data['Date Investigation Commenced'].isna().sum()

np.int64(11463)

In [36]:
data['Date of Investigation Completion'].isna().sum()

np.int64(11357)

In [37]:
data['Date of Near Miss'].isna().sum()

np.int64(2)

In [38]:
data['Date of Near Miss']

0        2012-01-03
1        2012-01-05
2        2012-01-06
3        2012-01-07
4        2012-01-07
            ...
12441    2020-04-04
12442    2020-04-21
12443    2020-04-29
12444    2020-04-23
12445    2020-04-29
Name: Date of Near Miss, Length: 12446, dtype: str

In [39]:
data['Date of Report']

0                     2012-01-03
1                     2012-01-05
2                     2012-01-06
3                     2012-01-09
4                     2012-01-23
                  ...
12441    2020-04-12 17:43:37.050
12442    2020-04-21 06:22:51.907
12443    2020-04-30 12:20:24.683
12444    2020-04-24 13:43:40.970
12445    2020-05-02 17:40:18.397
Name: Date of Report, Length: 12446, dtype: str

In [40]:
data['Date of Reporting'].isna().sum()

KeyError: 'Date of Reporting'

In [ ]:
ss