In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
data = pd.read_csv('/home/kiran/Downloads/cleaned-data/Raw-Data/Single_view_of_ship.csv')

In [3]:
data

,Name of Ship,First Event of Ship,Last Event of Ship,Life time of Ship in months,recency of First Event,recency of Last Event,nLARP-Total,nLARP_Closure,nLARP_Status_Accepted,nLARP_Status_Open,...,nADI_InjuryAccidentCategory_Lost Workday Case,nADI_InjuryAccidentCategory_Medical treatment case,nADI_InjuryAccidentCategory_Permanent partial disability,nADI_InjuryAccidentCategory_Permanent total disability,nADI_InjuryAccidentCategory_Restricted work case,nADI_InjuryAccidentCategory_Unknown,mADI_Closure-Occurrence-Report,mADI_Occurrence-Report,nInc,nCS
0,ACE SPAIN,2014-12-28,2017-03-06,26.251052,18.825849,39.787265,104.0,NaN,104.0,NaN,...,1.0,NaN,NaN,NaN,NaN,2.0,4.0,NaN,112.0,6216.0
1,ADITYA,2015-09-08,2020-05-23,56.477546,27.170989,1.215631,269.0,7.0,268.0,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,4.0,2.0,328.0,53628.0
2,AFRICAN SPOONBILL,2016-11-21,2019-12-29,37.224584,41.627138,6.012444,151.0,NaN,149.0,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,155.0,11935.0
3,AFRICAN TURACO,2016-03-19,2019-12-12,44.781207,33.511982,6.570977,71.0,NaN,70.0,NaN,...,NaN,NaN,NaN,NaN,NaN,6.0,6.0,2.0,94.0,4371.0
4,AL-BETROLEYA,2016-01-03,2020-05-19,52.502105,31.015011,1.347050,278.0,NaN,276.0,NaN,...,NaN,NaN,NaN,NaN,NaN,7.0,5.0,2.0,334.0,55611.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,X-PRESS MONTE ROSA,2015-07-03,2015-07-07,0.131420,24.969712,59.763034,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0
325,X-PRESS TAJUMULCO,2015-11-01,2017-03-12,16.328877,28.945153,39.590135,20.0,NaN,19.0,1.0,...,NaN,NaN,NaN,NaN,NaN,4.0,5.0,NaN,36.0,630.0
326,X-PRESS VESUVIO,2015-07-19,2017-01-27,18.333025,25.495390,41.035750,15.0,2.0,15.0,NaN,...,1.0,NaN,NaN,NaN,NaN,2.0,3.0,NaN,30.0,435.0
327,YERUPAJA,2015-06-30,2017-02-27,19.975770,24.871147,40.017249,32.0,6.0,32.0,NaN,...,NaN,5.0,NaN,NaN,NaN,1.0,6.0,1.0,50.0,1225.0
328,ZOLA,2020-03-21,2020-05-10,1.642744,81.578677,1.642744,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0

In [4]:
data.columns

Index(['Name of Ship', 'First Event of Ship', 'Last Event of Ship',
       'Life time of Ship in months', 'recency of First Event',
       'recency of Last Event', 'nLARP-Total', 'nLARP_Closure',
       'nLARP_Status_Accepted', 'nLARP_Status_Open', 'nLARP_Status_Rejected',
       'nLARP_Category_Safe act', 'nLARP_Category_Unsafe act',
       'mLARP_Accepted-Safe act', 'mLARP_Accepted-Safe act-Closure',
       'mLARP_Accepted-Unsafe act', 'mLARP_Accepted-Unsafe act-Closure',
       'mLARP_Open-Safe act', 'mLARP_Open-Unsafe act',
       'mLARP_Rejected-Safe act', 'mLARP_Rejected-Safe act-Closure',
       'mLARP_Rejected-Unsafe act', 'mLARP_Rejected-Unsafe act-Closure',
       'nNM-Total', 'nNM_Near Miss', 'nNM_Report',
       'nNM_Investigation Commenced', 'nNM_Investigation Completion',
       'nNM_Closure', 'nNM_Severity of incident_High',
       'nNM_Severity of incident_Low', 'nNM_Severity of incident_Medium',
       'nNM_Severity of incident_Unknown',
       'nNM_Probability_of_Reoccurence_Likely-High-Medium-Moderate',
       'nNM_Probability_of_Reoccurence_Others',
       'nNM_Probability_of_Reoccurence_Unlikely-Low-Marginal',
       'nNM_Probability_of_Reoccurence_Very Likely-Very High',
       'nNM_Probability_of_Reoccurence_Very Unlikely-Very Low',
       'nNM_Incident_Category_Potential_Catastrophic-Major-Extreme',
       'nNM_Incident_Category_Potential_Critical-Severe',
       'nNM_Incident_Category_Potential_Marginal-Moderate-Medium',
       'nNM_Incident_Category_Potential_Minor-Low-Slight',
       'nNM_Incident_Category_Potential_Others', 'nNM_Learning Potential_High',
       'nNM_Learning Potential_Low', 'nNM_Learning Potential_Medium',
       'nNM_Learning Potential_Unknown',
       'nNM_Further Investigation Required_No',
       'nNM_Further Investigation Required_Unknown',
       'nNM_Further Investigation Required_Yes',
       'nNM_Incident communicated to oil majors_No',
       'nNM_Incident communicated to oil majors_Unknown',
       'nNM_External authority reporting required_No',
       'nNM_External authority reporting required_Unknown',
       'nNM_External authority reporting required_Yes',
       'nNM_Potential incident to be shared with industry_No',
       'nNM_Potential incident to be shared with industry_Unknown', 'mNM_NM',
       'mNM_NM-R', 'mNM_NM-R-CL', 'mNM_NM-R-ICD-ICT', 'mNM_R', 'nADI-Total',
       'nADI_Occurrence', 'nADI_Report', 'nADI_Closure',
       'nADI_SeverityOfIncident_High', 'nADI_SeverityOfIncident_Low',
       'nADI_SeverityOfIncident_Medium', 'nADI_SeverityOfIncident_Unknown',
       'nADI_Possibility Recurrence_Likely',
       'nADI_Possibility Recurrence_Unknown',
       'nADI_Possibility Recurrence_Unlikely',
       'nADI_Possibility Recurrence_Very likely',
       'nADI_Possibility Recurrence_Very unlikely',
       'nADI_Incident Category_Catastrophic or extremely harmful',
       'nADI_Incident Category_Critical or severe harm',
       'nADI_Incident Category_Critical potential - Near miss',
       'nADI_Incident Category_Marginal or moderate harm',
       'nADI_Incident Category_Minor', 'nADI_LeariningPotential_High',
       'nADI_LeariningPotential_Low', 'nADI_LeariningPotential_Medium',
       'nADI_LeariningPotential_Unknown',
       'nADI_InjuryAccidentCategory_Fatality',
       'nADI_InjuryAccidentCategory_First aid case',
       'nADI_InjuryAccidentCategory_Lost Workday Case',
       'nADI_InjuryAccidentCategory_Medical treatment case',
       'nADI_InjuryAccidentCategory_Permanent partial disability',
       'nADI_InjuryAccidentCategory_Permanent total disability',
       'nADI_InjuryAccidentCategory_Restricted work case',
       'nADI_InjuryAccidentCategory_Unknown', 'mADI_Closure-Occurrence-Report',
       'mADI_Occurrence-Report', 'nInc', 'nCS'],
      dtype='str')

In [5]:
data.columns = data.columns.str.lower()

In [6]:
data.columns

Index(['name of ship', 'first event of ship', 'last event of ship',
       'life time of ship in months', 'recency of first event',
       'recency of last event', 'nlarp-total', 'nlarp_closure',
       'nlarp_status_accepted', 'nlarp_status_open', 'nlarp_status_rejected',
       'nlarp_category_safe act', 'nlarp_category_unsafe act',
       'mlarp_accepted-safe act', 'mlarp_accepted-safe act-closure',
       'mlarp_accepted-unsafe act', 'mlarp_accepted-unsafe act-closure',
       'mlarp_open-safe act', 'mlarp_open-unsafe act',
       'mlarp_rejected-safe act', 'mlarp_rejected-safe act-closure',
       'mlarp_rejected-unsafe act', 'mlarp_rejected-unsafe act-closure',
       'nnm-total', 'nnm_near miss', 'nnm_report',
       'nnm_investigation commenced', 'nnm_investigation completion',
       'nnm_closure', 'nnm_severity of incident_high',
       'nnm_severity of incident_low', 'nnm_severity of incident_medium',
       'nnm_severity of incident_unknown',
       'nnm_probability_of_reoccurence_likely-high-medium-moderate',
       'nnm_probability_of_reoccurence_others',
       'nnm_probability_of_reoccurence_unlikely-low-marginal',
       'nnm_probability_of_reoccurence_very likely-very high',
       'nnm_probability_of_reoccurence_very unlikely-very low',
       'nnm_incident_category_potential_catastrophic-major-extreme',
       'nnm_incident_category_potential_critical-severe',
       'nnm_incident_category_potential_marginal-moderate-medium',
       'nnm_incident_category_potential_minor-low-slight',
       'nnm_incident_category_potential_others', 'nnm_learning potential_high',
       'nnm_learning potential_low', 'nnm_learning potential_medium',
       'nnm_learning potential_unknown',
       'nnm_further investigation required_no',
       'nnm_further investigation required_unknown',
       'nnm_further investigation required_yes',
       'nnm_incident communicated to oil majors_no',
       'nnm_incident communicated to oil majors_unknown',
       'nnm_external authority reporting required_no',
       'nnm_external authority reporting required_unknown',
       'nnm_external authority reporting required_yes',
       'nnm_potential incident to be shared with industry_no',
       'nnm_potential incident to be shared with industry_unknown', 'mnm_nm',
       'mnm_nm-r', 'mnm_nm-r-cl', 'mnm_nm-r-icd-ict', 'mnm_r', 'nadi-total',
       'nadi_occurrence', 'nadi_report', 'nadi_closure',
       'nadi_severityofincident_high', 'nadi_severityofincident_low',
       'nadi_severityofincident_medium', 'nadi_severityofincident_unknown',
       'nadi_possibility recurrence_likely',
       'nadi_possibility recurrence_unknown',
       'nadi_possibility recurrence_unlikely',
       'nadi_possibility recurrence_very likely',
       'nadi_possibility recurrence_very unlikely',
       'nadi_incident category_catastrophic or extremely harmful',
       'nadi_incident category_critical or severe harm',
       'nadi_incident category_critical potential - near miss',
       'nadi_incident category_marginal or moderate harm',
       'nadi_incident category_minor', 'nadi_leariningpotential_high',
       'nadi_leariningpotential_low', 'nadi_leariningpotential_medium',
       'nadi_leariningpotential_unknown',
       'nadi_injuryaccidentcategory_fatality',
       'nadi_injuryaccidentcategory_first aid case',
       'nadi_injuryaccidentcategory_lost workday case',
       'nadi_injuryaccidentcategory_medical treatment case',
       'nadi_injuryaccidentcategory_permanent partial disability',
       'nadi_injuryaccidentcategory_permanent total disability',
       'nadi_injuryaccidentcategory_restricted work case',
       'nadi_injuryaccidentcategory_unknown', 'madi_closure-occurrence-report',
       'madi_occurrence-report', 'ninc', 'ncs'],
      dtype='str')

In [7]:
data.columns = data.columns.str.replace(' ', '_')

In [8]:
data.columns

Index(['name_of_ship', 'first_event_of_ship', 'last_event_of_ship',
       'life_time_of_ship_in_months', 'recency_of_first_event',
       'recency_of_last_event', 'nlarp-total', 'nlarp_closure',
       'nlarp_status_accepted', 'nlarp_status_open', 'nlarp_status_rejected',
       'nlarp_category_safe_act', 'nlarp_category_unsafe_act',
       'mlarp_accepted-safe_act', 'mlarp_accepted-safe_act-closure',
       'mlarp_accepted-unsafe_act', 'mlarp_accepted-unsafe_act-closure',
       'mlarp_open-safe_act', 'mlarp_open-unsafe_act',
       'mlarp_rejected-safe_act', 'mlarp_rejected-safe_act-closure',
       'mlarp_rejected-unsafe_act', 'mlarp_rejected-unsafe_act-closure',
       'nnm-total', 'nnm_near_miss', 'nnm_report',
       'nnm_investigation_commenced', 'nnm_investigation_completion',
       'nnm_closure', 'nnm_severity_of_incident_high',
       'nnm_severity_of_incident_low', 'nnm_severity_of_incident_medium',
       'nnm_severity_of_incident_unknown',
       'nnm_probability_of_reoccurence_likely-high-medium-moderate',
       'nnm_probability_of_reoccurence_others',
       'nnm_probability_of_reoccurence_unlikely-low-marginal',
       'nnm_probability_of_reoccurence_very_likely-very_high',
       'nnm_probability_of_reoccurence_very_unlikely-very_low',
       'nnm_incident_category_potential_catastrophic-major-extreme',
       'nnm_incident_category_potential_critical-severe',
       'nnm_incident_category_potential_marginal-moderate-medium',
       'nnm_incident_category_potential_minor-low-slight',
       'nnm_incident_category_potential_others', 'nnm_learning_potential_high',
       'nnm_learning_potential_low', 'nnm_learning_potential_medium',
       'nnm_learning_potential_unknown',
       'nnm_further_investigation_required_no',
       'nnm_further_investigation_required_unknown',
       'nnm_further_investigation_required_yes',
       'nnm_incident_communicated_to_oil_majors_no',
       'nnm_incident_communicated_to_oil_majors_unknown',
       'nnm_external_authority_reporting_required_no',
       'nnm_external_authority_reporting_required_unknown',
       'nnm_external_authority_reporting_required_yes',
       'nnm_potential_incident_to_be_shared_with_industry_no',
       'nnm_potential_incident_to_be_shared_with_industry_unknown', 'mnm_nm',
       'mnm_nm-r', 'mnm_nm-r-cl', 'mnm_nm-r-icd-ict', 'mnm_r', 'nadi-total',
       'nadi_occurrence', 'nadi_report', 'nadi_closure',
       'nadi_severityofincident_high', 'nadi_severityofincident_low',
       'nadi_severityofincident_medium', 'nadi_severityofincident_unknown',
       'nadi_possibility_recurrence_likely',
       'nadi_possibility_recurrence_unknown',
       'nadi_possibility_recurrence_unlikely',
       'nadi_possibility_recurrence_very_likely',
       'nadi_possibility_recurrence_very_unlikely',
       'nadi_incident_category_catastrophic_or_extremely_harmful',
       'nadi_incident_category_critical_or_severe_harm',
       'nadi_incident_category_critical_potential_-_near_miss',
       'nadi_incident_category_marginal_or_moderate_harm',
       'nadi_incident_category_minor', 'nadi_leariningpotential_high',
       'nadi_leariningpotential_low', 'nadi_leariningpotential_medium',
       'nadi_leariningpotential_unknown',
       'nadi_injuryaccidentcategory_fatality',
       'nadi_injuryaccidentcategory_first_aid_case',
       'nadi_injuryaccidentcategory_lost_workday_case',
       'nadi_injuryaccidentcategory_medical_treatment_case',
       'nadi_injuryaccidentcategory_permanent_partial_disability',
       'nadi_injuryaccidentcategory_permanent_total_disability',
       'nadi_injuryaccidentcategory_restricted_work_case',
       'nadi_injuryaccidentcategory_unknown', 'madi_closure-occurrence-report',
       'madi_occurrence-report', 'ninc', 'ncs'],
      dtype='str')

In [9]:
data.columns = data.columns.str.replace('-', '_')

In [10]:
data.columns

Index(['name_of_ship', 'first_event_of_ship', 'last_event_of_ship',
       'life_time_of_ship_in_months', 'recency_of_first_event',
       'recency_of_last_event', 'nlarp_total', 'nlarp_closure',
       'nlarp_status_accepted', 'nlarp_status_open', 'nlarp_status_rejected',
       'nlarp_category_safe_act', 'nlarp_category_unsafe_act',
       'mlarp_accepted_safe_act', 'mlarp_accepted_safe_act_closure',
       'mlarp_accepted_unsafe_act', 'mlarp_accepted_unsafe_act_closure',
       'mlarp_open_safe_act', 'mlarp_open_unsafe_act',
       'mlarp_rejected_safe_act', 'mlarp_rejected_safe_act_closure',
       'mlarp_rejected_unsafe_act', 'mlarp_rejected_unsafe_act_closure',
       'nnm_total', 'nnm_near_miss', 'nnm_report',
       'nnm_investigation_commenced', 'nnm_investigation_completion',
       'nnm_closure', 'nnm_severity_of_incident_high',
       'nnm_severity_of_incident_low', 'nnm_severity_of_incident_medium',
       'nnm_severity_of_incident_unknown',
       'nnm_probability_of_reoccurence_likely_high_medium_moderate',
       'nnm_probability_of_reoccurence_others',
       'nnm_probability_of_reoccurence_unlikely_low_marginal',
       'nnm_probability_of_reoccurence_very_likely_very_high',
       'nnm_probability_of_reoccurence_very_unlikely_very_low',
       'nnm_incident_category_potential_catastrophic_major_extreme',
       'nnm_incident_category_potential_critical_severe',
       'nnm_incident_category_potential_marginal_moderate_medium',
       'nnm_incident_category_potential_minor_low_slight',
       'nnm_incident_category_potential_others', 'nnm_learning_potential_high',
       'nnm_learning_potential_low', 'nnm_learning_potential_medium',
       'nnm_learning_potential_unknown',
       'nnm_further_investigation_required_no',
       'nnm_further_investigation_required_unknown',
       'nnm_further_investigation_required_yes',
       'nnm_incident_communicated_to_oil_majors_no',
       'nnm_incident_communicated_to_oil_majors_unknown',
       'nnm_external_authority_reporting_required_no',
       'nnm_external_authority_reporting_required_unknown',
       'nnm_external_authority_reporting_required_yes',
       'nnm_potential_incident_to_be_shared_with_industry_no',
       'nnm_potential_incident_to_be_shared_with_industry_unknown', 'mnm_nm',
       'mnm_nm_r', 'mnm_nm_r_cl', 'mnm_nm_r_icd_ict', 'mnm_r', 'nadi_total',
       'nadi_occurrence', 'nadi_report', 'nadi_closure',
       'nadi_severityofincident_high', 'nadi_severityofincident_low',
       'nadi_severityofincident_medium', 'nadi_severityofincident_unknown',
       'nadi_possibility_recurrence_likely',
       'nadi_possibility_recurrence_unknown',
       'nadi_possibility_recurrence_unlikely',
       'nadi_possibility_recurrence_very_likely',
       'nadi_possibility_recurrence_very_unlikely',
       'nadi_incident_category_catastrophic_or_extremely_harmful',
       'nadi_incident_category_critical_or_severe_harm',
       'nadi_incident_category_critical_potential___near_miss',
       'nadi_incident_category_marginal_or_moderate_harm',
       'nadi_incident_category_minor', 'nadi_leariningpotential_high',
       'nadi_leariningpotential_low', 'nadi_leariningpotential_medium',
       'nadi_leariningpotential_unknown',
       'nadi_injuryaccidentcategory_fatality',
       'nadi_injuryaccidentcategory_first_aid_case',
       'nadi_injuryaccidentcategory_lost_workday_case',
       'nadi_injuryaccidentcategory_medical_treatment_case',
       'nadi_injuryaccidentcategory_permanent_partial_disability',
       'nadi_injuryaccidentcategory_permanent_total_disability',
       'nadi_injuryaccidentcategory_restricted_work_case',
       'nadi_injuryaccidentcategory_unknown', 'madi_closure_occurrence_report',
       'madi_occurrence_report', 'ninc', 'ncs'],
      dtype='str')

In [11]:
data.columns = data.columns.str.replace('__', '_')

In [12]:
data.columns

Index(['name_of_ship', 'first_event_of_ship', 'last_event_of_ship',
       'life_time_of_ship_in_months', 'recency_of_first_event',
       'recency_of_last_event', 'nlarp_total', 'nlarp_closure',
       'nlarp_status_accepted', 'nlarp_status_open', 'nlarp_status_rejected',
       'nlarp_category_safe_act', 'nlarp_category_unsafe_act',
       'mlarp_accepted_safe_act', 'mlarp_accepted_safe_act_closure',
       'mlarp_accepted_unsafe_act', 'mlarp_accepted_unsafe_act_closure',
       'mlarp_open_safe_act', 'mlarp_open_unsafe_act',
       'mlarp_rejected_safe_act', 'mlarp_rejected_safe_act_closure',
       'mlarp_rejected_unsafe_act', 'mlarp_rejected_unsafe_act_closure',
       'nnm_total', 'nnm_near_miss', 'nnm_report',
       'nnm_investigation_commenced', 'nnm_investigation_completion',
       'nnm_closure', 'nnm_severity_of_incident_high',
       'nnm_severity_of_incident_low', 'nnm_severity_of_incident_medium',
       'nnm_severity_of_incident_unknown',
       'nnm_probability_of_reoccurence_likely_high_medium_moderate',
       'nnm_probability_of_reoccurence_others',
       'nnm_probability_of_reoccurence_unlikely_low_marginal',
       'nnm_probability_of_reoccurence_very_likely_very_high',
       'nnm_probability_of_reoccurence_very_unlikely_very_low',
       'nnm_incident_category_potential_catastrophic_major_extreme',
       'nnm_incident_category_potential_critical_severe',
       'nnm_incident_category_potential_marginal_moderate_medium',
       'nnm_incident_category_potential_minor_low_slight',
       'nnm_incident_category_potential_others', 'nnm_learning_potential_high',
       'nnm_learning_potential_low', 'nnm_learning_potential_medium',
       'nnm_learning_potential_unknown',
       'nnm_further_investigation_required_no',
       'nnm_further_investigation_required_unknown',
       'nnm_further_investigation_required_yes',
       'nnm_incident_communicated_to_oil_majors_no',
       'nnm_incident_communicated_to_oil_majors_unknown',
       'nnm_external_authority_reporting_required_no',
       'nnm_external_authority_reporting_required_unknown',
       'nnm_external_authority_reporting_required_yes',
       'nnm_potential_incident_to_be_shared_with_industry_no',
       'nnm_potential_incident_to_be_shared_with_industry_unknown', 'mnm_nm',
       'mnm_nm_r', 'mnm_nm_r_cl', 'mnm_nm_r_icd_ict', 'mnm_r', 'nadi_total',
       'nadi_occurrence', 'nadi_report', 'nadi_closure',
       'nadi_severityofincident_high', 'nadi_severityofincident_low',
       'nadi_severityofincident_medium', 'nadi_severityofincident_unknown',
       'nadi_possibility_recurrence_likely',
       'nadi_possibility_recurrence_unknown',
       'nadi_possibility_recurrence_unlikely',
       'nadi_possibility_recurrence_very_likely',
       'nadi_possibility_recurrence_very_unlikely',
       'nadi_incident_category_catastrophic_or_extremely_harmful',
       'nadi_incident_category_critical_or_severe_harm',
       'nadi_incident_category_critical_potential__near_miss',
       'nadi_incident_category_marginal_or_moderate_harm',
       'nadi_incident_category_minor', 'nadi_leariningpotential_high',
       'nadi_leariningpotential_low', 'nadi_leariningpotential_medium',
       'nadi_leariningpotential_unknown',
       'nadi_injuryaccidentcategory_fatality',
       'nadi_injuryaccidentcategory_first_aid_case',
       'nadi_injuryaccidentcategory_lost_workday_case',
       'nadi_injuryaccidentcategory_medical_treatment_case',
       'nadi_injuryaccidentcategory_permanent_partial_disability',
       'nadi_injuryaccidentcategory_permanent_total_disability',
       'nadi_injuryaccidentcategory_restricted_work_case',
       'nadi_injuryaccidentcategory_unknown', 'madi_closure_occurrence_report',
       'madi_occurrence_report', 'ninc', 'ncs'],
      dtype='str')

In [13]:
data.columns = data.columns.str.strip()

In [14]:
data.columns

Index(['name_of_ship', 'first_event_of_ship', 'last_event_of_ship',
       'life_time_of_ship_in_months', 'recency_of_first_event',
       'recency_of_last_event', 'nlarp_total', 'nlarp_closure',
       'nlarp_status_accepted', 'nlarp_status_open', 'nlarp_status_rejected',
       'nlarp_category_safe_act', 'nlarp_category_unsafe_act',
       'mlarp_accepted_safe_act', 'mlarp_accepted_safe_act_closure',
       'mlarp_accepted_unsafe_act', 'mlarp_accepted_unsafe_act_closure',
       'mlarp_open_safe_act', 'mlarp_open_unsafe_act',
       'mlarp_rejected_safe_act', 'mlarp_rejected_safe_act_closure',
       'mlarp_rejected_unsafe_act', 'mlarp_rejected_unsafe_act_closure',
       'nnm_total', 'nnm_near_miss', 'nnm_report',
       'nnm_investigation_commenced', 'nnm_investigation_completion',
       'nnm_closure', 'nnm_severity_of_incident_high',
       'nnm_severity_of_incident_low', 'nnm_severity_of_incident_medium',
       'nnm_severity_of_incident_unknown',
       'nnm_probability_of_reoccurence_likely_high_medium_moderate',
       'nnm_probability_of_reoccurence_others',
       'nnm_probability_of_reoccurence_unlikely_low_marginal',
       'nnm_probability_of_reoccurence_very_likely_very_high',
       'nnm_probability_of_reoccurence_very_unlikely_very_low',
       'nnm_incident_category_potential_catastrophic_major_extreme',
       'nnm_incident_category_potential_critical_severe',
       'nnm_incident_category_potential_marginal_moderate_medium',
       'nnm_incident_category_potential_minor_low_slight',
       'nnm_incident_category_potential_others', 'nnm_learning_potential_high',
       'nnm_learning_potential_low', 'nnm_learning_potential_medium',
       'nnm_learning_potential_unknown',
       'nnm_further_investigation_required_no',
       'nnm_further_investigation_required_unknown',
       'nnm_further_investigation_required_yes',
       'nnm_incident_communicated_to_oil_majors_no',
       'nnm_incident_communicated_to_oil_majors_unknown',
       'nnm_external_authority_reporting_required_no',
       'nnm_external_authority_reporting_required_unknown',
       'nnm_external_authority_reporting_required_yes',
       'nnm_potential_incident_to_be_shared_with_industry_no',
       'nnm_potential_incident_to_be_shared_with_industry_unknown', 'mnm_nm',
       'mnm_nm_r', 'mnm_nm_r_cl', 'mnm_nm_r_icd_ict', 'mnm_r', 'nadi_total',
       'nadi_occurrence', 'nadi_report', 'nadi_closure',
       'nadi_severityofincident_high', 'nadi_severityofincident_low',
       'nadi_severityofincident_medium', 'nadi_severityofincident_unknown',
       'nadi_possibility_recurrence_likely',
       'nadi_possibility_recurrence_unknown',
       'nadi_possibility_recurrence_unlikely',
       'nadi_possibility_recurrence_very_likely',
       'nadi_possibility_recurrence_very_unlikely',
       'nadi_incident_category_catastrophic_or_extremely_harmful',
       'nadi_incident_category_critical_or_severe_harm',
       'nadi_incident_category_critical_potential__near_miss',
       'nadi_incident_category_marginal_or_moderate_harm',
       'nadi_incident_category_minor', 'nadi_leariningpotential_high',
       'nadi_leariningpotential_low', 'nadi_leariningpotential_medium',
       'nadi_leariningpotential_unknown',
       'nadi_injuryaccidentcategory_fatality',
       'nadi_injuryaccidentcategory_first_aid_case',
       'nadi_injuryaccidentcategory_lost_workday_case',
       'nadi_injuryaccidentcategory_medical_treatment_case',
       'nadi_injuryaccidentcategory_permanent_partial_disability',
       'nadi_injuryaccidentcategory_permanent_total_disability',
       'nadi_injuryaccidentcategory_restricted_work_case',
       'nadi_injuryaccidentcategory_unknown', 'madi_closure_occurrence_report',
       'madi_occurrence_report', 'ninc', 'ncs'],
      dtype='str')

In [15]:
data.columns = data.columns.str.replace('nnm', 'nm')
data.columns = data.columns.str.replace('nadi', 'adi')
data.columns = data.columns.str.replace('nlarp', 'larp')

In [16]:
data.columns

Index(['name_of_ship', 'first_event_of_ship', 'last_event_of_ship',
       'life_time_of_ship_in_months', 'recency_of_first_event',
       'recency_of_last_event', 'larp_total', 'larp_closure',
       'larp_status_accepted', 'larp_status_open', 'larp_status_rejected',
       'larp_category_safe_act', 'larp_category_unsafe_act',
       'mlarp_accepted_safe_act', 'mlarp_accepted_safe_act_closure',
       'mlarp_accepted_unsafe_act', 'mlarp_accepted_unsafe_act_closure',
       'mlarp_open_safe_act', 'mlarp_open_unsafe_act',
       'mlarp_rejected_safe_act', 'mlarp_rejected_safe_act_closure',
       'mlarp_rejected_unsafe_act', 'mlarp_rejected_unsafe_act_closure',
       'nm_total', 'nm_near_miss', 'nm_report', 'nm_investigation_commenced',
       'nm_investigation_completion', 'nm_closure',
       'nm_severity_of_incident_high', 'nm_severity_of_incident_low',
       'nm_severity_of_incident_medium', 'nm_severity_of_incident_unknown',
       'nm_probability_of_reoccurence_likely_high_medium_moderate',
       'nm_probability_of_reoccurence_others',
       'nm_probability_of_reoccurence_unlikely_low_marginal',
       'nm_probability_of_reoccurence_very_likely_very_high',
       'nm_probability_of_reoccurence_very_unlikely_very_low',
       'nm_incident_category_potential_catastrophic_major_extreme',
       'nm_incident_category_potential_critical_severe',
       'nm_incident_category_potential_marginal_moderate_medium',
       'nm_incident_category_potential_minor_low_slight',
       'nm_incident_category_potential_others', 'nm_learning_potential_high',
       'nm_learning_potential_low', 'nm_learning_potential_medium',
       'nm_learning_potential_unknown', 'nm_further_investigation_required_no',
       'nm_further_investigation_required_unknown',
       'nm_further_investigation_required_yes',
       'nm_incident_communicated_to_oil_majors_no',
       'nm_incident_communicated_to_oil_majors_unknown',
       'nm_external_authority_reporting_required_no',
       'nm_external_authority_reporting_required_unknown',
       'nm_external_authority_reporting_required_yes',
       'nm_potential_incident_to_be_shared_with_industry_no',
       'nm_potential_incident_to_be_shared_with_industry_unknown', 'mnm_nm',
       'mnm_nm_r', 'mnm_nm_r_cl', 'mnm_nm_r_icd_ict', 'mnm_r', 'adi_total',
       'adi_occurrence', 'adi_report', 'adi_closure',
       'adi_severityofincident_high', 'adi_severityofincident_low',
       'adi_severityofincident_medium', 'adi_severityofincident_unknown',
       'adi_possibility_recurrence_likely',
       'adi_possibility_recurrence_unknown',
       'adi_possibility_recurrence_unlikely',
       'adi_possibility_recurrence_very_likely',
       'adi_possibility_recurrence_very_unlikely',
       'adi_incident_category_catastrophic_or_extremely_harmful',
       'adi_incident_category_critical_or_severe_harm',
       'adi_incident_category_critical_potential__near_miss',
       'adi_incident_category_marginal_or_moderate_harm',
       'adi_incident_category_minor', 'adi_leariningpotential_high',
       'adi_leariningpotential_low', 'adi_leariningpotential_medium',
       'adi_leariningpotential_unknown', 'adi_injuryaccidentcategory_fatality',
       'adi_injuryaccidentcategory_first_aid_case',
       'adi_injuryaccidentcategory_lost_workday_case',
       'adi_injuryaccidentcategory_medical_treatment_case',
       'adi_injuryaccidentcategory_permanent_partial_disability',
       'adi_injuryaccidentcategory_permanent_total_disability',
       'adi_injuryaccidentcategory_restricted_work_case',
       'adi_injuryaccidentcategory_unknown', 'madi_closure_occurrence_report',
       'madi_occurrence_report', 'ninc', 'ncs'],
      dtype='str')

In [17]:
data.columns = data.columns.str.replace('severity_of_incident', 'severity')
data.columns = data.columns.str.replace('probability_of_reoccurence', 'prob')
data.columns = data.columns.str.replace('incident_category_potential', 'category')
data.columns = data.columns.str.replace('learning_potential', 'learning')

In [18]:
data.columns

Index(['name_of_ship', 'first_event_of_ship', 'last_event_of_ship',
       'life_time_of_ship_in_months', 'recency_of_first_event',
       'recency_of_last_event', 'larp_total', 'larp_closure',
       'larp_status_accepted', 'larp_status_open', 'larp_status_rejected',
       'larp_category_safe_act', 'larp_category_unsafe_act',
       'mlarp_accepted_safe_act', 'mlarp_accepted_safe_act_closure',
       'mlarp_accepted_unsafe_act', 'mlarp_accepted_unsafe_act_closure',
       'mlarp_open_safe_act', 'mlarp_open_unsafe_act',
       'mlarp_rejected_safe_act', 'mlarp_rejected_safe_act_closure',
       'mlarp_rejected_unsafe_act', 'mlarp_rejected_unsafe_act_closure',
       'nm_total', 'nm_near_miss', 'nm_report', 'nm_investigation_commenced',
       'nm_investigation_completion', 'nm_closure', 'nm_severity_high',
       'nm_severity_low', 'nm_severity_medium', 'nm_severity_unknown',
       'nm_prob_likely_high_medium_moderate', 'nm_prob_others',
       'nm_prob_unlikely_low_marginal', 'nm_prob_very_likely_very_high',
       'nm_prob_very_unlikely_very_low',
       'nm_category_catastrophic_major_extreme', 'nm_category_critical_severe',
       'nm_category_marginal_moderate_medium', 'nm_category_minor_low_slight',
       'nm_category_others', 'nm_learning_high', 'nm_learning_low',
       'nm_learning_medium', 'nm_learning_unknown',
       'nm_further_investigation_required_no',
       'nm_further_investigation_required_unknown',
       'nm_further_investigation_required_yes',
       'nm_incident_communicated_to_oil_majors_no',
       'nm_incident_communicated_to_oil_majors_unknown',
       'nm_external_authority_reporting_required_no',
       'nm_external_authority_reporting_required_unknown',
       'nm_external_authority_reporting_required_yes',
       'nm_potential_incident_to_be_shared_with_industry_no',
       'nm_potential_incident_to_be_shared_with_industry_unknown', 'mnm_nm',
       'mnm_nm_r', 'mnm_nm_r_cl', 'mnm_nm_r_icd_ict', 'mnm_r', 'adi_total',
       'adi_occurrence', 'adi_report', 'adi_closure',
       'adi_severityofincident_high', 'adi_severityofincident_low',
       'adi_severityofincident_medium', 'adi_severityofincident_unknown',
       'adi_possibility_recurrence_likely',
       'adi_possibility_recurrence_unknown',
       'adi_possibility_recurrence_unlikely',
       'adi_possibility_recurrence_very_likely',
       'adi_possibility_recurrence_very_unlikely',
       'adi_incident_category_catastrophic_or_extremely_harmful',
       'adi_incident_category_critical_or_severe_harm',
       'adi_incident_category_critical_potential__near_miss',
       'adi_incident_category_marginal_or_moderate_harm',
       'adi_incident_category_minor', 'adi_leariningpotential_high',
       'adi_leariningpotential_low', 'adi_leariningpotential_medium',
       'adi_leariningpotential_unknown', 'adi_injuryaccidentcategory_fatality',
       'adi_injuryaccidentcategory_first_aid_case',
       'adi_injuryaccidentcategory_lost_workday_case',
       'adi_injuryaccidentcategory_medical_treatment_case',
       'adi_injuryaccidentcategory_permanent_partial_disability',
       'adi_injuryaccidentcategory_permanent_total_disability',
       'adi_injuryaccidentcategory_restricted_work_case',
       'adi_injuryaccidentcategory_unknown', 'madi_closure_occurrence_report',
       'madi_occurrence_report', 'ninc', 'ncs'],
      dtype='str')

In [19]:
data = data.rename(columns={
    'name_of_ship': 'ship_name',
    'first_event_of_ship': 'first_event',
    'last_event_of_ship': 'last_event',
    'life_time_of_ship_in_months': 'lifetime_months'
})

In [20]:
data.columns

Index(['ship_name', 'first_event', 'last_event', 'lifetime_months',
       'recency_of_first_event', 'recency_of_last_event', 'larp_total',
       'larp_closure', 'larp_status_accepted', 'larp_status_open',
       'larp_status_rejected', 'larp_category_safe_act',
       'larp_category_unsafe_act', 'mlarp_accepted_safe_act',
       'mlarp_accepted_safe_act_closure', 'mlarp_accepted_unsafe_act',
       'mlarp_accepted_unsafe_act_closure', 'mlarp_open_safe_act',
       'mlarp_open_unsafe_act', 'mlarp_rejected_safe_act',
       'mlarp_rejected_safe_act_closure', 'mlarp_rejected_unsafe_act',
       'mlarp_rejected_unsafe_act_closure', 'nm_total', 'nm_near_miss',
       'nm_report', 'nm_investigation_commenced',
       'nm_investigation_completion', 'nm_closure', 'nm_severity_high',
       'nm_severity_low', 'nm_severity_medium', 'nm_severity_unknown',
       'nm_prob_likely_high_medium_moderate', 'nm_prob_others',
       'nm_prob_unlikely_low_marginal', 'nm_prob_very_likely_very_high',
       'nm_prob_very_unlikely_very_low',
       'nm_category_catastrophic_major_extreme', 'nm_category_critical_severe',
       'nm_category_marginal_moderate_medium', 'nm_category_minor_low_slight',
       'nm_category_others', 'nm_learning_high', 'nm_learning_low',
       'nm_learning_medium', 'nm_learning_unknown',
       'nm_further_investigation_required_no',
       'nm_further_investigation_required_unknown',
       'nm_further_investigation_required_yes',
       'nm_incident_communicated_to_oil_majors_no',
       'nm_incident_communicated_to_oil_majors_unknown',
       'nm_external_authority_reporting_required_no',
       'nm_external_authority_reporting_required_unknown',
       'nm_external_authority_reporting_required_yes',
       'nm_potential_incident_to_be_shared_with_industry_no',
       'nm_potential_incident_to_be_shared_with_industry_unknown', 'mnm_nm',
       'mnm_nm_r', 'mnm_nm_r_cl', 'mnm_nm_r_icd_ict', 'mnm_r', 'adi_total',
       'adi_occurrence', 'adi_report', 'adi_closure',
       'adi_severityofincident_high', 'adi_severityofincident_low',
       'adi_severityofincident_medium', 'adi_severityofincident_unknown',
       'adi_possibility_recurrence_likely',
       'adi_possibility_recurrence_unknown',
       'adi_possibility_recurrence_unlikely',
       'adi_possibility_recurrence_very_likely',
       'adi_possibility_recurrence_very_unlikely',
       'adi_incident_category_catastrophic_or_extremely_harmful',
       'adi_incident_category_critical_or_severe_harm',
       'adi_incident_category_critical_potential__near_miss',
       'adi_incident_category_marginal_or_moderate_harm',
       'adi_incident_category_minor', 'adi_leariningpotential_high',
       'adi_leariningpotential_low', 'adi_leariningpotential_medium',
       'adi_leariningpotential_unknown', 'adi_injuryaccidentcategory_fatality',
       'adi_injuryaccidentcategory_first_aid_case',
       'adi_injuryaccidentcategory_lost_workday_case',
       'adi_injuryaccidentcategory_medical_treatment_case',
       'adi_injuryaccidentcategory_permanent_partial_disability',
       'adi_injuryaccidentcategory_permanent_total_disability',
       'adi_injuryaccidentcategory_restricted_work_case',
       'adi_injuryaccidentcategory_unknown', 'madi_closure_occurrence_report',
       'madi_occurrence_report', 'ninc', 'ncs'],
      dtype='str')

In [21]:
len(data.columns)

96

In [22]:
data['adi_closure']

0      4.0
1      4.0
2      1.0
3      6.0
4      5.0
      ...
324    NaN
325    5.0
326    3.0
327    6.0
328    NaN
Name: adi_closure, Length: 329, dtype: float64

In [23]:
data['adi_closure'].value_counts()

adi_closure
1.0     57
4.0     29
3.0     29
2.0     27
5.0     18
7.0     16
6.0     12
8.0     10
12.0    10
13.0     8
10.0     6
9.0      6
11.0     5
16.0     3
14.0     2
19.0     1
17.0     1
15.0     1
18.0     1
Name: count, dtype: int64

In [24]:
data['adi_closure'].isna().sum()

np.int64(87)

In [25]:
data['adi_incident_category_catastrophic_or_extremely_harmful']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
324   NaN
325   NaN
326   NaN
327   NaN
328   NaN
Name: adi_incident_category_catastrophic_or_extremely_harmful, Length: 329, dtype: float64

In [26]:
data['adi_incident_category_catastrophic_or_extremely_harmful'].value_counts()

adi_incident_category_catastrophic_or_extremely_harmful
1.0    10
2.0     2
Name: count, dtype: int64

In [27]:
data['adi_incident_category_critical_or_severe_harm']

0      NaN
1      1.0
2      NaN
3      2.0
4      NaN
      ...
324    NaN
325    NaN
326    NaN
327    NaN
328    NaN
Name: adi_incident_category_critical_or_severe_harm, Length: 329, dtype: float64

In [28]:
data['adi_incident_category_critical_or_severe_harm'].isna().sum()

np.int64(293)

In [29]:
data['adi_incident_category_critical_potential__near_miss']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
324   NaN
325   NaN
326   NaN
327   NaN
328   NaN
Name: adi_incident_category_critical_potential__near_miss, Length: 329, dtype: float64

In [30]:
data['adi_incident_category_critical_potential__near_miss'].isna().sum()

np.int64(328)

In [31]:
data['adi_incident_category_marginal_or_moderate_harm']

0      1.0
1      2.0
2      NaN
3      1.0
4      3.0
      ...
324    NaN
325    2.0
326    NaN
327    3.0
328    NaN
Name: adi_incident_category_marginal_or_moderate_harm, Length: 329, dtype: float64

In [33]:
data['adi_incident_category_marginal_or_moderate_harm'].value_counts()

adi_incident_category_marginal_or_moderate_harm
1.0     64
2.0     43
3.0     38
4.0     17
5.0      6
6.0      5
9.0      4
10.0     1
7.0      1
Name: count, dtype: int64

In [32]:
data['adi_incident_category_marginal_or_moderate_harm'].isna().sum()

np.int64(150)

In [34]:
data['adi_incident_category_minor']

0      3.0
1      3.0
2      1.0
3      5.0
4      4.0
      ...
324    NaN
325    3.0
326    3.0
327    4.0
328    NaN
Name: adi_incident_category_minor, Length: 329, dtype: float64

In [35]:
data['adi_incident_category_minor'].isna().sum()

np.int64(99)

In [36]:
data['adi_injuryaccidentcategory_fatality']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
324   NaN
325   NaN
326   NaN
327   NaN
328   NaN
Name: adi_injuryaccidentcategory_fatality, Length: 329, dtype: float64

In [37]:
data['adi_incident_category_minor']

0      3.0
1      3.0
2      1.0
3      5.0
4      4.0
      ...
324    NaN
325    3.0
326    3.0
327    4.0
328    NaN
Name: adi_incident_category_minor, Length: 329, dtype: float64

In [38]:
data['adi_injuryaccidentcategory_fatality'].isna().sum()

np.int64(295)

In [39]:
data['adi_injuryaccidentcategory_first_aid_case']

0      1.0
1      2.0
2      NaN
3      2.0
4      NaN
      ...
324    NaN
325    1.0
326    NaN
327    1.0
328    NaN
Name: adi_injuryaccidentcategory_first_aid_case, Length: 329, dtype: float64

In [40]:
data['adi_injuryaccidentcategory_first_aid_case'].isna().sum()

np.int64(196)

In [41]:
data.describe()

,lifetime_months,recency_of_first_event,recency_of_last_event,larp_total,larp_closure,larp_status_accepted,larp_status_open,larp_status_rejected,larp_category_safe_act,larp_category_unsafe_act,...,adi_injuryaccidentcategory_lost_workday_case,adi_injuryaccidentcategory_medical_treatment_case,adi_injuryaccidentcategory_permanent_partial_disability,adi_injuryaccidentcategory_permanent_total_disability,adi_injuryaccidentcategory_restricted_work_case,adi_injuryaccidentcategory_unknown,madi_closure_occurrence_report,madi_occurrence_report,ninc,ncs
count,329.000000,329.000000,329.000000,274.000000,86.000000,253.000000,52.000000,95.000000,264.000000,274.000000,...,69.000000,84.000000,4.0,1.0,37.000000,228.000000,242.000000,122.000000,329.000000,329.000000
mean,27.367363,48.027649,9.472193,219.284672,65.197674,225.924901,49.134615,3.894737,45.821970,175.135036,...,1.318841,1.714286,1.0,1.0,1.135135,3.723684,4.983471,1.680328,217.155015,49115.702128
std,19.948938,21.769824,15.890022,205.723914,109.356279,207.202029,70.748388,6.465084,54.957593,165.159796,...,0.652884,1.146723,0.0,NaN,0.346583,2.906466,4.088205,1.077696,226.822921,93200.954241
min,0.032855,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,10.086449,27.335264,1.117066,46.250000,2.000000,52.000000,8.000000,1.000000,10.000000,36.250000,...,1.000000,1.000000,1.0,1.0,1.000000,2.000000,2.000000,1.000000,35.000000,595.000000
50%,22.308466,46.128257,1.938438,166.500000,7.000000,179.000000,22.000000,2.000000,33.000000,139.500000,...,1.000000,1.000000,1.0,1.0,1.000000,3.000000,4.000000,1.000000,145.000000,10440.000000
75%,45.076901,69.093821,6.143863,330.250000,79.000000,331.000000,45.750000,4.000000,64.000000,262.750000,...,1.000000,2.000000,1.0,1.0,1.000000,5.000000,7.000000,2.000000,355.000000,62835.000000
max,70.933695,83.057147,69.028111,1142.000000,449.000000,1117.000000,351.000000,54.000000,608.000000,906.000000,...,4.000000,7.000000,1.0,1.0,2.000000,15.000000,19.000000,7.000000,1179.000000,694431.000000

In [42]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 96 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   ship_name                                                 329 non-null    str
 1   first_event                                               329 non-null    str
 2   last_event                                                329 non-null    str
 3   lifetime_months                                           329 non-null    float64
 4   recency_of_first_event                                    329 non-null    float64
 5   recency_of_last_event                                     329 non-null    float64
 6   larp_total                                                274 non-null    float64
 7   larp_closure                                              86 non-null     float64
 8   larp_status_accepted                                      253 non-null    float64
 9   larp_status_open                                          52 non-null     float64
 10  larp_status_rejected                                      95 non-null     float64
 11  larp_category_safe_act                                    264 non-null    float64
 12  larp_category_unsafe_act                                  274 non-null    float64
 13  mlarp_accepted_safe_act                                   225 non-null    float64
 14  mlarp_accepted_safe_act_closure                           56 non-null     float64
 15  mlarp_accepted_unsafe_act                                 241 non-null    float64
 16  mlarp_accepted_unsafe_act_closure                         79 non-null     float64
 17  mlarp_open_safe_act                                       46 non-null     float64
 18  mlarp_open_unsafe_act                                     49 non-null     float64
 19  mlarp_rejected_safe_act                                   47 non-null     float64
 20  mlarp_rejected_safe_act_closure                           3 non-null      float64
 21  mlarp_rejected_unsafe_act                                 69 non-null     float64
 22  mlarp_rejected_unsafe_act_closure                         8 non-null      float64
 23  nm_total                                                  319 non-null    float64
 24  nm_near_miss                                              313 non-null    float64
 25  nm_report                                                 319 non-null    float64
 26  nm_investigation_commenced                                1 non-null      float64
 27  nm_investigation_completion                               1 non-null      float64
 28  nm_closure                                                60 non-null     float64
 29  nm_severity_high                                          142 non-null    float64
 30  nm_severity_low                                           270 non-null    float64
 31  nm_severity_medium                                        251 non-null    float64
 32  nm_severity_unknown                                       255 non-null    float64
 33  nm_prob_likely_high_medium_moderate                       288 non-null    float64
 34  nm_prob_others                                            97 non-null     float64
 35  nm_prob_unlikely_low_marginal                             288 non-null    float64
 36  nm_prob_very_likely_very_high                             179 non-null    float64
 37  nm_prob_very_unlikely_very_low                            231 non-null    float64
 38  nm_category_catastrophic_major_extreme                    222 non-null    float64
 39  nm_category_critical_severe                               217 non-null    float64
 40  nm_category_marginal_moderate_medium                      275 non-null    float64
 41  nm_category_minor_low_slight                              307 non-null    float64
 42  nm_category_others                                        4 non-null      float64
 43  nm_learning_high                                          56 non-null     float64
 44  nm_learning_low                                           281 non-null    float64
 45  nm_learning_medium                                        241 non-null    float64
 46  nm_learning_unknown                                       275 non-null    float64
 47  nm_further_investigation_required_no                      149 non-null    float64
 48  nm_further_investigation_required_unknown                 308 non-null    float64
 49  nm_further_investigation_required_yes                     1 non-null      float64
 50  nm_incident_communicated_to_oil_majors_no                 149 non-null    float64
 51  nm_incident_communicated_to_oil_majors_unknown            308 non-null    float64
 52  nm_external_authority_reporting_required_no               149 non-null    float64
 53  nm_external_authority_reporting_required_unknown          308 non-null    float64
 54  nm_external_authority_reporting_required_yes              1 non-null      float64
 55  nm_potential_incident_to_be_shared_with_industry_no       149 non-null    float64
 56  nm_potential_incident_to_be_shared_with_industry_unknown  308 non-null    float64
 57  mnm_nm                                                    1 non-null      float64
 58  mnm_nm_r                                                  310 non-null    float64
 59  mnm_nm_r_cl                                               60 non-null     float64
 60  mnm_nm_r_icd_ict                                          1 non-null      float64
 61  mnm_r                                                     48 non-null     float64
 62  adi_total                                                 260 non-null    float64
 63  adi_occurrence                                            260 non-null    float64
 64  adi_report                                                260 non-null    float64
 65  adi_closure                                               242 non-null    float64
 66  adi_severityofincident_high                               82 non-null     float64
 67  adi_severityofincident_low                                176 non-null    float64
 68  adi_severityofincident_medium                             192 non-null    float64
 69  adi_severityofincident_unknown                            113 non-null    float64
 70  adi_possibility_recurrence_likely                         156 non-null    float64
 71  adi_possibility_recurrence_unknown                        20 non-null     float64
 72  adi_possibility_recurrence_unlikely                       200 non-null    float64
 73  adi_possibility_recurrence_very_likely                    92 non-null     float64
 74  adi_possibility_recurrence_very_unlikely                  157 non-null    float64
 75  adi_incident_category_catastrophic_or_extremely_harmful   12 non-null     float64
 76  adi_incident_category_critical_or_severe_harm             36 non-null     float64
 77  adi_incident_category_critical_potential__near_miss       1 non-null      float64
 78  adi_incident_category_marginal_or_moderate_harm           179 non-null    float64
 79  adi_incident_category_minor                               230 non-null    float64
 80  adi_leariningpotential_high                               35 non-null     float64
 81  adi_leariningpotential_low                                189 non-null    float64
 82  adi_leariningpotential_medium                             177 non-null    float64
 83  adi_leariningpotential_unknown                            155 non-null    float64
 84  adi_injuryaccidentcategory_fatality                       34 non-null     float64
 85  adi_injuryaccidentcategory_first_aid_case                 133 non-null    float64
 86  adi_injuryaccidentcategory_lost_workday_case              69 non-null     float64
 87  adi_injuryaccidentcategory_medical_treatment_case         84 non-null     float64
 88  adi_injuryaccidentcategory_permanent_partial_disability   4 non-null      float64
 89  adi_injuryaccidentcategory_permanent_total_disability     1 non-null      float64
 90  adi_injuryaccidentcategory_restricted_work_case           37 non-null     float64
 91  adi_injuryaccidentcategory_unknown                        228 non-null    float64
 92  madi_closure_occurrence_report                            242 non-null    float64
 93  madi_occurrence_report                                    122 non-null    float64
 94  ninc                                                      329 non-null    float64
 95  ncs                                                       329 non-null    float64
dtypes: float64(93), str(3)
memory usage: 246.9 KB

In [43]:
data['adi_injuryaccidentcategory_lost_workday_case']

0      1.0
1      NaN
2      NaN
3      NaN
4      NaN
      ...
324    NaN
325    NaN
326    1.0
327    NaN
328    NaN
Name: adi_injuryaccidentcategory_lost_workday_case, Length: 329, dtype: float64

In [44]:
data['adi_injuryaccidentcategory_lost_workday_case'].isna().sum()

np.int64(260)

In [45]:
data['adi_injuryaccidentcategory_medical_treatment_case']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
324    NaN
325    NaN
326    NaN
327    5.0
328    NaN
Name: adi_injuryaccidentcategory_medical_treatment_case, Length: 329, dtype: float64

In [46]:
data['adi_injuryaccidentcategory_medical_treatment_case'].isna().sum()

np.int64(245)

In [47]:
data['adi_injuryaccidentcategory_permanent_partial_disability']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
324   NaN
325   NaN
326   NaN
327   NaN
328   NaN
Name: adi_injuryaccidentcategory_permanent_partial_disability, Length: 329, dtype: float64

In [48]:
data['adi_injuryaccidentcategory_medical_treatment_case']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
324    NaN
325    NaN
326    NaN
327    5.0
328    NaN
Name: adi_injuryaccidentcategory_medical_treatment_case, Length: 329, dtype: float64